/**
 * Game plan schema extensions — situation plays and assignments.
 *
 * The game plan is organized by situation columns (1st down, 2nd short,
 * 3rd long, red zone, etc.). Each column holds play cards that the
 * coordinator adds from the playbook or from the Play Suggester.
 *
 * When the coordinator publishes, downstream outputs auto-generate:
 *   - Player assignments (per position group)
 *   - Scout team cards (opponent plays to run in practice)
 *
 * This file extends the base schema with the additional tables needed.
 * Import from db/schema.ts which re-exports these.
 */

import { index, integer, jsonb, pgTable, text, timestamp, uuid, varchar } from 'drizzle-orm/pg-core';
import { programs, gamePlans, playbookPlays } from './schema';

// ─── Game plan plays (plays assigned to situation columns) ──

export const gamePlanPlays = pgTable(
  'game_plan_plays',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    programId: uuid('program_id')
      .notNull()
      .references(() => programs.id, { onDelete: 'cascade' }),
    gamePlanId: uuid('game_plan_id')
      .notNull()
      .references(() => gamePlans.id, { onDelete: 'cascade' }),
    playbookPlayId: uuid('playbook_play_id')
      .references(() => playbookPlays.id, { onDelete: 'set null' }),
    situation: varchar('situation', { length: 30 }).notNull(),
    // Ordering within the situation column
    sortOrder: integer('sort_order').notNull().default(0),
    // Play details (denormalized for display — source of truth is playbookPlayId)
    playName: text('play_name').notNull(),
    formation: text('formation'),
    playType: varchar('play_type', { length: 20 }),
    // AI suggester reasoning (if this play was suggested, not manually added)
    suggesterReasoning: text('suggester_reasoning'),
    suggesterConfidence: varchar('suggester_confidence', { length: 20 }),
    // Opponent tendency this play attacks
    attacksTendency: text('attacks_tendency'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('game_plan_plays_plan_situation_idx').on(t.gamePlanId, t.situation),
    index('game_plan_plays_program_idx').on(t.programId),
  ],
);

// ─── Game plan assignments (per-player deliverables) ────────

export const gamePlanAssignments = pgTable(
  'game_plan_assignments',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    programId: uuid('program_id')
      .notNull()
      .references(() => programs.id, { onDelete: 'cascade' }),
    gamePlanId: uuid('game_plan_id')
      .notNull()
      .references(() => gamePlans.id, { onDelete: 'cascade' }),
    // Position group this assignment targets
    positionGroup: varchar('position_group', { length: 10 }).notNull(),
    situation: varchar('situation', { length: 30 }).notNull(),
    // Plain-language assignment (generated by LLM from coach's compact call)
    assignmentText: text('assignment_text').notNull(),
    // The plays associated with this assignment
    relatedPlayIds: jsonb('related_play_ids'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('game_plan_assignments_plan_idx').on(t.gamePlanId),
    index('game_plan_assignments_program_idx').on(t.programId),
  ],
);
