/**
 * Practice script — the bridge from "scouting insights" to "what the
 * team actually does on the practice field" Mon-Thu.
 *
 * The walkthrough tells the coach WHAT the opponent does. The call
 * sheet tells the coach WHAT TO CALL on Friday. The practice script
 * tells the coach HOW TO REHEARSE for it during the week.
 *
 * Generated by Claude in one shot from the walkthrough's insights +
 * call sheet. Pure data — no DB persistence yet (caller can stash on
 * the opponent row if they want a "remembered" script).
 */

import { z } from 'zod';
import type { Walkthrough } from './insights';

// ─── Types ──────────────────────────────────────────────────

export type PracticeDayName = 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday';

/**
 * One drill within a period — a concrete rep block tied back to a
 * specific walkthrough insight when possible. The `scoutLook` field is
 * the look we ask the scout team to give (defense/offense), so this
 * doubles as a scout-team script.
 */
export interface PracticeDrill {
  /** Drill name a coach would recognize ("Mesh vs Cover 3 read"). */
  name: string;
  /** Number of reps to schedule. */
  reps: number;
  /** What the scout team simulates ("Cover 3 with the FS widening"). */
  scoutLook: string;
  /** One sentence explaining why this drill matters this week. */
  rationale: string;
  /** ID of the walkthrough insight this drill exploits, when applicable. */
  insightId?: string;
}

/**
 * A practice period — Individual / Group / Team / Situational. Coaches
 * structure practice in 8-12 minute blocks with a focus and reps.
 */
export interface PracticePeriod {
  /** Period name ("Individual", "7-on-7", "Team", "Red Zone", "2-Minute"). */
  name: string;
  /** Block length in minutes. */
  durationMinutes: number;
  /** What this period is meant to accomplish ("install Mesh family"). */
  focus: string;
  /** Concrete drills run in this period. Empty = open-ended walk-through. */
  drills: PracticeDrill[];
}

/**
 * One day of practice.
 */
export interface PracticeDay {
  day: PracticeDayName;
  /** One-word theme ("Install", "Heavy", "Situational", "Walk-through"). */
  theme: string;
  periods: PracticePeriod[];
}

/**
 * The full week's practice script.
 */
export interface PracticeScript {
  opponentId: string;
  opponentName: string;
  /** ISO date of the Monday we're scripting for. */
  weekOfMonday: string;
  /** One-paragraph theme for the whole week. */
  weekTheme: string;
  days: PracticeDay[];
  generatedAt: string;
}

// ─── Zod schemas (used by the API route + tests) ────────────

export const practiceDrillSchema = z.object({
  name: z.string().min(3).max(80),
  reps: z.number().int().positive().max(40),
  scoutLook: z.string().min(3).max(120),
  rationale: z.string().min(10).max(200),
  insightId: z.string().optional(),
});

export const practicePeriodSchema = z.object({
  name: z.string().min(2).max(40),
  durationMinutes: z.number().int().positive().max(60),
  focus: z.string().min(5).max(120),
  drills: z.array(practiceDrillSchema).max(8),
});

export const practiceDaySchema = z.object({
  day: z.enum(['Monday', 'Tuesday', 'Wednesday', 'Thursday']),
  theme: z.string().min(3).max(40),
  periods: z.array(practicePeriodSchema).min(1).max(8),
});

/**
 * Schema for what Claude returns. We attach opponentId / opponentName /
 * generatedAt server-side so Claude doesn't have to hallucinate them.
 */
export const practiceScriptResponseSchema = z.object({
  weekTheme: z.string().min(20).max(400),
  days: z.array(practiceDaySchema).length(4),
});

// ─── Prompt context (what Claude needs to know) ────────────

/**
 * Compact, prompt-friendly view of a walkthrough — strips video URLs,
 * overlays, tracks, and per-play CV measurements that aren't useful
 * for scripting practice. Keeps only the football decisions: tendency
 * headlines, narratives, recommendations, and the bucketed call sheet.
 */
export function buildPromptContext(walkthrough: Walkthrough): string {
  const lines: string[] = [
    `Opponent: ${walkthrough.opponentName}`,
    `Plays of film analyzed: ${walkthrough.playsAnalyzed}`,
    '',
    'INSIGHTS (ranked by exploitability):',
  ];

  for (const ins of walkthrough.insights) {
    lines.push('');
    lines.push(`#${ins.rank} [${ins.id}] ${ins.headline}`);
    lines.push(`  ${ins.narrative}`);
    if (ins.recommendations.length > 0) {
      lines.push('  Calls to install:');
      for (const rec of ins.recommendations) {
        lines.push(`    • ${rec.call} — ${rec.situation}`);
        lines.push(`      (${rec.rationale})`);
      }
    }
  }

  if (walkthrough.callSheet && walkthrough.callSheet.buckets.length > 0) {
    lines.push('');
    lines.push('CALL SHEET BUCKETS (for situational periods):');
    for (const bucket of walkthrough.callSheet.buckets) {
      lines.push(`  ${bucket.bucket}:`);
      for (const rec of bucket.recommendations) {
        lines.push(`    - ${rec.call} (insight: ${rec.insightId})`);
      }
    }
  }

  return lines.join('\n');
}

// ─── Plain-text rendering for export ────────────────────────

/**
 * Render the script as plain text the coach can paste into a doc, print,
 * or text to their staff. Each day gets its own block; periods are
 * indented; drills hang off periods.
 */
export function renderScriptAsText(script: PracticeScript): string {
  const lines: string[] = [
    `PRACTICE SCRIPT — ${script.opponentName}`,
    `Week of ${script.weekOfMonday}`,
    '',
    `THEME: ${script.weekTheme}`,
    '',
  ];

  for (const day of script.days) {
    lines.push(`── ${day.day.toUpperCase()} (${day.theme}) ──`);
    for (const period of day.periods) {
      lines.push(`  ${period.name} · ${period.durationMinutes} min`);
      lines.push(`    Focus: ${period.focus}`);
      for (const drill of period.drills) {
        lines.push(`      • ${drill.name} (×${drill.reps})`);
        lines.push(`        Scout look: ${drill.scoutLook}`);
        lines.push(`        Why: ${drill.rationale}`);
      }
    }
    lines.push('');
  }

  return lines.join('\n').trimEnd();
}

/**
 * Compute the Monday of the current week (or the next Monday if today
 * is Friday/Saturday/Sunday — practice scripts are forward-looking).
 * Returns ISO date "YYYY-MM-DD".
 */
export function nextPracticeMonday(now: Date = new Date()): string {
  const day = now.getDay(); // 0 = Sun
  // Mon=1 so target offset from current day:
  // Sun(0): +1, Mon(1): 0, Tue(2): -1 (this week's Mon), Wed(3): -2,
  // Thu(4): -3, Fri(5): +3 (next Mon), Sat(6): +2 (next Mon).
  const offset = day === 0 ? 1 : day <= 4 ? 1 - day : 8 - day;
  const monday = new Date(now);
  monday.setDate(now.getDate() + offset);
  return monday.toISOString().slice(0, 10);
}
